# Generated by Django 5.2.8 on 2025-11-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('available', models.IntegerField()),
                ('image_path', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
